// Structs
mod list_node;
mod tree_node;

// Solutions
mod contains_duplicate;
mod missing_number;
mod find_disappeared_numbers;
mod single_number;
mod climb_stairs;
mod max_profit;
mod max_sub_array;
mod sum_range;
mod count_bits;
mod middle_node;
mod reverse_list;
mod is_palindrome;
mod merge_two_lists;
mod search;
mod next_greatest_letter;
mod two_sum;
mod remove_elements;
mod delete_duplicates;
mod can_attend_meetings;
mod peak_index_in_mountain_array;
mod spiral_order;
mod sorted_squares;
mod find_duplicates;
mod set_zeroes;
mod find_duplicate;
mod average_of_levels;
mod is_same_tree;
mod min_depth;
mod has_path_sum;
mod merge_k_lists;
mod backspace_compare;

struct Solution;